version: '3'
services:
   app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - mynetwork

   web:
     image: nginx
     ports: 
       - 80:80
     volumes: 
       - ./nginx.conf:/etc/nginx/nginx.conf  
     networks:
       - mynetwork

networks:
   mynetwork:
       driver: bridge
  # angular-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:80

