version: '3.8'
services:
  
  fronted:
     build: .
     ports: 
        - 8080:4200

  
  # angular-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:80

  # web:
  #   image: nginx
  #   ports: 
  #     - 80:80
  #   volumes: 
  #     - nginx.conf /etc/nginx/conf.d/default.conf  